steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/payment-integration', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/payment-integration']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'payment-integration', '--image', 'gcr.io/$PROJECT_ID/payment-integration', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']
