openapi: 3.0.0
info:
  title: Payment Gateway API
  version: 1.0.0
paths:
  /deposit:
    post:
      summary: Deposit money
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                currency:
                  type: string
                gateway:
                  type: string
      responses:
        '200':
          description: Successful deposit
        '400':
          description: Invalid request
        '500':
          description: Internal server error
  /withdraw:
    post:
      summary: Withdraw money
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                gateway:
                  type: string
      responses:
        '200':
          description: Successful withdrawal
        '400':
          description: Invalid request
        '500':
          description: Internal server error
  /callback/gateway_a:
    post:
      summary: Handle callback from gateway A
      responses:
        '200':
          description: Successful callback handling
        '500':
          description: Internal server error

  /callback/gateway_b:
    post:
      summary: Handle callback from gateway B
      responses:
        '200':
          description: Successful callback handling
        '500':
          description: Internal server error
